### PR TITLE
Tech/update linting setup

### PR DESCRIPTION
**Pull request by papandreou**
Prompted by https://github.com/unexpectedjs/unexpected-knex/pull/66

Blocked by unexpected-fs, which prevents upgrading past node.js 6 :worried:

### CODE REVIEW

**Comment by joelmukuthu** [comment]
Hey @papandreou, do you want to give this another go, now that I've managed to upgrade past Node.js 6 ([ref](https://github.com/unexpectedjs/unexpected-knex/commit/fc7b554a9691f204ade96f492e343468182a899e))?

**Comment by papandreou** [comment]
@joelmukuthu, there!

**Comment by joelmukuthu** [comment]
How awesome you are! :hugs: :shipit:

**Comment by papandreou** [comment]
@joelmukuthu, yw! I guess you might want to upgrade to prettier 2.x while you're at it, but I left that out of this PR.

**Comment by papandreou** [comment]
I can also turn depfu back on if you want? I turned it off because there wasn't much action here :)

**Comment by joelmukuthu** [comment]
Yes, let's turn it back on although I don't often react too fast to it for dev dependencies. And we can also handle the prettier 2.x update that way :)

And yeah, besides keeping this up to date with Knex I don't think I'll be doing too much in the way of new features unfortunately.

**Comment by papandreou** [comment]
It's back on!

**Pull request merged**
