### PR TITLE
Upgrade knex to ^2

### PR DESCRIPTION
**Pull request by thyen**
This PR:
- Upgrades node runtime to 18.17
- Updates the `knex` dependency to ^2.5.1
  - This is a BREAKING CHANGE matching the breaking change version from knex

### CODE REVIEW

**Comment by joelmukuthu** [comment]
Thanks for the PR Thyen! I need to fix up some things here before I can deploy a new version. In the meantime, do you know in what version knex changed the paths? I'd like to know what other knex versions could potentially be supported in the peer-dependency range.

**Comment by thyen** [comment]
File structured change PR https://github.com/knex/knex/pull/4178
Looks like it was on version 0.95.0

**Comment by thyen** [comment]
Updated the PR with appropriate peer dependency range

**Comment by joelmukuthu** [comment]
I've update dev deps and gotten tests to run again, would you please rebase your branch Thyen? You can skip commit https://github.com/unexpectedjs/unexpected-knex/pull/142/commits/c30640c585e5288aa73c5cdb07a69122beacfceb that's already applied on master. In the commit that upgrades Knex, you'll also need to update this path in the tests:

https://github.com/unexpectedjs/unexpected-knex/blob/70b221c8f2770652aeace6c654af82fb0af2fe05/test/unexpected-knex.spec.js#L13

I think the new path is `knex/lib/migrations/util/import-file.js`.

**Comment by thyen** [comment]
Donezo! Rebasted with your master changes and updates the .spec.js import reference

**Comment by joelmukuthu** [comment]
This path also needs an update https://github.com/unexpectedjs/unexpected-knex/blob/b9961816d0c1bc73c6a53e1016b79ca54143b2c8/test/unexpected-knex.spec.js#L3 

And then run `npm run lint:fix` to fix the formatting error :)

**Comment by thyen** [comment]
Applied the lint fixes, updated the node version on `Dockerfile` and ran the tests locally to confirm it all passes, I _think_ we're good now

**Comment by joelmukuthu** [comment]
Perfect, thanks Thyen!

**Comment by joelmukuthu** [comment]
Released in v5.0.0

**Pull request merged**
